name: Release

on:
    push:
        branches:
            - staging
            - master

jobs:
    release:
        name: Release GitHub Actions
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                 GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
              with:
                tag_name: ${{ github.ref }}
                release_name: Release ${{ github.ref }}
                draft: false
                prerelease: false
            - name: Release GitHub Actions
              uses: technote-space/release-github-actions@v6
              with:
                GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}